import axios from 'axios'
import Head from 'next/head'
import Catalog from '../../components/catalog/Catalog'
import Footer from '../../components/footer/Footer'
import Hero from '../../components/hero/Hero'
import Navbar from '../../components/navbar/Navbar'

export default function Home({ meals }) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Navbar />
        <Hero />
        <Catalog meals={meals} />
        <Footer />
      </main>
    </>
  )
}


export async function getServerSideProps(){
  
  const { data } = await axios.get(`http://localhost:3000/api/meal`)

  return {
    props: {
      meals: data
    }
  }
}